version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi-container
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-container
    ports:
      - "8501:8501"
    networks:
      - mynetwork
    depends_on:
      - fastapi

networks:
  mynetwork:
    driver: bridge
