# This is a Docker Compose file for deploying a FastAPI and Streamlit application.
# It defines two services: fastapi and streamlit, each with its own container.

version: '3.8'

services:
  fastapi:
    image: rohitsontamu/iqa-cicd-api:${IMAGE_TAG}
    container_name: fastapi-container
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  streamlit:
    image: rohitsontamu/iqa-cicd-streamlit:${IMAGE_TAG}
    container_name: streamlit-container
    ports:
      - "8501:8501"
    networks:
      - mynetwork
    depends_on:
      - fastapi

networks:
  mynetwork:
    driver: bridge

